export const REWRITE_PROVIDER_ORDER = [
  "dashscope",
  "deepseek",
  "openai",
  "moonshot",
  "zhipu",
  "siliconflow",
  "volcengine",
  "qianfan",
  "hunyuan",
  "minimax",
  "xiaomi",
  "openrouter",
  "custom",
];
export const AUTO_MODEL_VALUE = "__auto_latest__";
export const REWRITE_PROVIDER_PRESETS = {
  dashscope: {
    label: "DashScope 通义千问",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    model: "qwen-plus",
    models: ["qwen-plus", "qwen-max", "qwen-turbo", "qwen-long"],
    applyUrl: "https://help.aliyun.com/zh/model-studio/get-api-key/",
    balanceUrl: "https://bailian.console.aliyun.com/",
  },
  deepseek: {
    label: "DeepSeek",
    baseUrl: "https://api.deepseek.com",
    model: "deepseek-chat",
    models: ["deepseek-chat", "deepseek-reasoner"],
    applyUrl: "https://platform.deepseek.com/api_keys",
    balanceUrl: "https://platform.deepseek.com/usage",
  },
  openai: {
    label: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-4o-mini",
    models: ["gpt-4o-mini", "gpt-4o", "gpt-4.1-mini"],
    applyUrl: "https://platform.openai.com/api-keys",
    balanceUrl: "https://platform.openai.com/settings/organization/billing/overview",
  },
  moonshot: {
    label: "Kimi / Moonshot",
    baseUrl: "https://api.moonshot.cn/v1",
    model: "moonshot-v1-8k",
    models: ["moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k", "kimi-k2-turbo-preview"],
    applyUrl: "https://platform.moonshot.cn/console/api-keys",
    balanceUrl: "https://platform.moonshot.cn/console/account",
  },
  zhipu: {
    label: "智谱 GLM",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    model: "glm-4-flash",
    models: ["glm-4-flash", "glm-4-plus", "glm-4-air", "glm-4.5-flash"],
    applyUrl: "https://bigmodel.cn/usercenter/proj-mgmt/apikeys",
    balanceUrl: "https://bigmodel.cn/usercenter/overview",
  },
  siliconflow: {
    label: "硅基流动 SiliconFlow",
    baseUrl: "https://api.siliconflow.cn/v1",
    model: "Qwen/Qwen2.5-72B-Instruct",
    models: ["Qwen/Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-V3", "deepseek-ai/DeepSeek-R1"],
    applyUrl: "https://cloud.siliconflow.cn/account/ak",
    balanceUrl: "https://cloud.siliconflow.cn/account/bill",
  },
  volcengine: {
    label: "火山方舟 / 豆包",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    model: "doubao-seed-1-6-250615",
    models: ["doubao-seed-1-6-250615", "doubao-seed-1-6-flash-250615", "doubao-pro-32k"],
    applyUrl: "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
    balanceUrl: "https://console.volcengine.com/finance",
  },
  qianfan: {
    label: "百度千帆",
    baseUrl: "https://qianfan.baidubce.com/v2",
    model: "ernie-4.0-turbo-8k",
    models: ["ernie-4.0-turbo-8k", "ernie-4.0-8k", "ernie-speed-8k"],
    applyUrl: "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
    balanceUrl: "https://console.bce.baidu.com/finance/",
  },
  hunyuan: {
    label: "腾讯混元",
    baseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    model: "hunyuan-turbos-latest",
    models: ["hunyuan-turbos-latest", "hunyuan-large", "hunyuan-standard"],
    applyUrl: "https://console.cloud.tencent.com/hunyuan/api-key",
    balanceUrl: "https://console.cloud.tencent.com/expense/overview",
  },
  minimax: {
    label: "MiniMax",
    baseUrl: "https://api.minimaxi.com/v1",
    model: "MiniMax-M2.5",
    models: ["MiniMax-M2.5", "MiniMax-M2", "MiniMax-Text-01"],
    applyUrl: "https://platform.minimaxi.com/",
    balanceUrl: "https://platform.minimaxi.com/",
  },
  xiaomi: {
    label: "小米 MiMo",
    baseUrl: "https://api.xiaomimimo.com/v1",
    model: "mimo-v2.5-pro",
    models: ["mimo-v2.5-pro", "mimo-v2.5", "mimo-v2.5-omni"],
    applyUrl: "https://platform.xiaomimimo.com",
    balanceUrl: "https://platform.xiaomimimo.com",
  },
  openrouter: {
    label: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    model: "openrouter/auto",
    models: ["openrouter/auto", "openai/gpt-4o-mini", "deepseek/deepseek-chat", "qwen/qwen-plus"],
    applyUrl: "https://openrouter.ai/settings/keys",
    balanceUrl: "https://openrouter.ai/settings/credits",
  },
  custom: {
    label: "自定义 OpenAI 兼容接口",
    baseUrl: "http://127.0.0.1:11434/v1",
    model: "",
    models: [],
    applyUrl: "",
    balanceUrl: "",
    custom: true,
  },
};
