const BASE_CONFIG = {
  fontFamily: "Microsoft YaHei",
  fontSize: 88,
  x: 50,
  y: 64,
  maxLines: 2,
  animationSpeed: 1,
  backgroundOpacity: 72,
  outlineEnabled: true,
  shadowEnabled: true,
};

const TEMPLATE_DEFS = [
  {
    id: "rolling-focus",
    name: "滚动聚焦",
    description: "当前句放大提亮，上下文平滑滚动，适合知识口播与课程。",
    scene: "知识口播 / 教育",
    primary: "#F8FAFC",
    accent: "#B7FF5A",
    muted: "#7B8493",
    tokenMode: "line",
    timingMode: "sentence",
    renderMode: "rolling-focus",
    layout: "rolling-stack",
    motion: "focus-scroll",
    supportedTiming: ["sentence"],
    requiresWordTiming: false,
    defaultParams: { fontSize: 78, y: 54, maxLines: 3, animationSpeed: 0.9 },
    source: "CapCut 2024-2026 lyric/focus layouts + deterministic Remotion timing primitives",
    license: "Integration code: project-owned; timing primitives: Remotion reference (see SOURCE.md)",
  },
  {
    id: "rolling-focus-subtitle",
    name: "滚动聚焦大字字幕",
    description: "黑底左侧 5 行语义队列，当前短句以白色粗体和 ▶ 聚焦，按校正时间轴连续上滚。",
    scene: "知识口播 / 英语教学",
    primary: "#FFFFFF",
    accent: "#FFFFFF",
    muted: "#B7B7B7",
    tokenMode: "line",
    timingMode: "sentence",
    renderMode: "rolling-focus-left",
    layout: "left-focus-queue",
    motion: "vertical-queue",
    supportedTiming: ["sentence", "word"],
    requiresWordTiming: false,
    defaultParams: {
      fontSize: 58,
      x: 5,
      y: 50,
      maxLines: 1,
      animationSpeed: 1,
      backgroundOpacity: 0,
      outlineEnabled: false,
      shadowEnabled: false,
      contextRows: 5,
      transitionMs: 220,
      leadMs: 90,
      resetGapMs: 1200,
    },
    source: "User-provided 2026 reference video 7月15日.mp4; structure reimplemented from measured frames",
    license: "Original project integration; reference video supplies visual behavior only and no code/assets are copied",
  },
  {
    id: "word-highlight",
    name: "逐词聚焦",
    description: "短语稳定显示，当前朗读词以强调色和轻微缩放聚焦。",
    scene: "短视频口播 / 教程",
    primary: "#FFFFFF",
    accent: "#FFD84D",
    muted: "#D7DBE2",
    tokenMode: "word",
    timingMode: "word",
    renderMode: "word-highlight",
    layout: "phrase-center",
    motion: "word-focus",
    supportedTiming: ["word", "sentence"],
    requiresWordTiming: true,
    defaultParams: { fontSize: 94, y: 61, maxLines: 2, animationSpeed: 1 },
    source: "Remotion official TikTok caption template + remotion-captions-themes PopTheme",
    license: "Adapted integration: MIT source; Remotion runtime is not bundled",
  },
  {
    id: "karaoke-sweep",
    name: "流光跟读",
    description: "强调色按真实逐词时间从左向右连续扫过整句。",
    scene: "口播 / 歌词 / 跟读",
    primary: "#EEF2F7",
    accent: "#6CF0C2",
    muted: "#FFFFFF",
    tokenMode: "word",
    timingMode: "word",
    renderMode: "karaoke-sweep",
    layout: "phrase-center",
    motion: "karaoke-fill",
    supportedTiming: ["word"],
    requiresWordTiming: true,
    defaultParams: { fontSize: 86, y: 68, animationSpeed: 1 },
    source: "remotion-captions-themes KaraokeTheme (2026) + FFmpeg/libass karaoke fill",
    license: "MIT source logic; libass is used only as the deterministic renderer",
  },
  {
    id: "center-statement",
    name: "编辑部金句",
    description: "单句居中、克制淡入与位移，强调观点而不制造网页动画感。",
    scene: "观点 / 演讲 / 发布会",
    primary: "#FFFFFF",
    accent: "#A7C7FF",
    muted: "#CBD2DD",
    tokenMode: "line",
    timingMode: "sentence",
    renderMode: "center-statement",
    layout: "statement-center",
    motion: "editorial-enter",
    supportedTiming: ["sentence"],
    requiresWordTiming: false,
    defaultParams: { fontSize: 82, y: 50, maxLines: 2, outlineEnabled: false, shadowEnabled: true },
    source: "OpenAI and Apple 2024-2026 launch-event editorial typography benchmark",
    license: "Original integration from documented modern visual benchmark; no brand assets",
  },
  {
    id: "keyword-emphasis",
    name: "重点词冲击",
    description: "普通词稳定，重点词按时间轴克制放大，适合结论和强观点。",
    scene: "商业口播 / 结论",
    primary: "#FFFFFF",
    accent: "#FFDD55",
    muted: "#D9DEE8",
    tokenMode: "phrase",
    timingMode: "word",
    renderMode: "keyword-emphasis",
    layout: "keyword-center",
    motion: "keyword-punch",
    supportedTiming: ["word", "sentence"],
    requiresWordTiming: false,
    defaultParams: { fontSize: 96, y: 60, animationSpeed: 0.92 },
    source: "Captions/Submagic 2024-2026 AI-emphasis patterns + remotion-captions-themes emphasis logic",
    license: "MIT timing logic; product visuals used only as post-2022 benchmark",
  },
  {
    id: "phrase-pop",
    name: "短语节拍",
    description: "每次显示 2–5 个词，短语按口播节奏成组出现。",
    scene: "快节奏短视频 / 干货",
    primary: "#FFFFFF",
    accent: "#FFB12B",
    muted: "#FFFFFF",
    tokenMode: "phrase",
    timingMode: "word",
    renderMode: "phrase-pop",
    layout: "phrase-center",
    motion: "phrase-spring",
    supportedTiming: ["word", "sentence"],
    requiresWordTiming: false,
    defaultParams: { fontSize: 98, y: 61, animationSpeed: 1.05 },
    source: "2026 Alex Hormozi sample + Remotion official spring/page grouping",
    license: "Original integration of observed post-2022 layout; Remotion reference only",
  },
  {
    id: "dialogue-two-line",
    name: "双人访谈",
    description: "说话人标签与双行正文分层，当前说话人突出且避开人物面部。",
    scene: "访谈 / 播客 / 对话",
    primary: "#FFFFFF",
    accent: "#8BD3FF",
    muted: "#B7C0CF",
    tokenMode: "line",
    timingMode: "sentence",
    renderMode: "dialogue-two-line",
    layout: "dialogue-lower",
    motion: "speaker-switch",
    supportedTiming: ["sentence", "word"],
    requiresWordTiming: false,
    defaultParams: { fontSize: 62, y: 77, maxLines: 2, backgroundOpacity: 78 },
    source: "Diary of a CEO/Captions podcast layouts + remotion-captions-themes PodcastTheme",
    license: "MIT component structure; generic names and project-owned styling",
  },
  {
    id: "documentary-minimal",
    name: "纪录片极简",
    description: "底部安全区、精细字距与低干扰淡入，适合故事和风景。",
    scene: "纪录片 / 故事 / 风景",
    primary: "#F7F7F5",
    accent: "#F7F7F5",
    muted: "#D6D6D2",
    tokenMode: "line",
    timingMode: "sentence",
    renderMode: "documentary-minimal",
    layout: "safe-lower",
    motion: "soft-fade",
    supportedTiming: ["sentence"],
    requiresWordTiming: false,
    defaultParams: { fontSize: 54, y: 82, maxLines: 2, outlineEnabled: false, backgroundOpacity: 0 },
    source: "Apple/OpenAI 2024-2026 restrained caption benchmark + deterministic fade primitive",
    license: "Original integration from documented modern visual benchmark",
  },
  {
    id: "caption-card",
    name: "自适应卡片",
    description: "半透明圆角感卡片随文字尺寸变化，适合步骤、重点与结论。",
    scene: "课程重点 / 步骤说明",
    primary: "#FFFFFF",
    accent: "#B5FF70",
    muted: "#FFFFFF",
    tokenMode: "line",
    timingMode: "sentence",
    renderMode: "caption-card",
    layout: "adaptive-card",
    motion: "card-enter",
    supportedTiming: ["sentence", "word"],
    requiresWordTiming: false,
    defaultParams: { fontSize: 72, y: 67, maxLines: 2, backgroundOpacity: 74, outlineEnabled: false },
    source: "CapCut/Captions/OpusClip 2024-2026 adaptive caption-card benchmark",
    license: "Original integration; no copied brand template or asset",
  },
  {
    id: "keyword-tags",
    name: "知识点标签",
    description: "主句稳定排版，数字和关键词以克制胶囊标签强调。",
    scene: "知识点 / 数字 / 结论",
    primary: "#FFFFFF",
    accent: "#8CE1FF",
    muted: "#D8DEE8",
    tokenMode: "phrase",
    timingMode: "word",
    renderMode: "keyword-tags",
    layout: "tagged-statement",
    motion: "tag-reveal",
    supportedTiming: ["sentence", "word"],
    requiresWordTiming: false,
    defaultParams: { fontSize: 76, y: 62, maxLines: 2, backgroundOpacity: 88 },
    source: "Captions/OpusClip/Submagic 2024-2026 keyword-highlight benchmark",
    license: "Original integration of generic modern pattern; no brand assets",
  },
];

export const KINETIC_TEXT_EFFECTS = TEMPLATE_DEFS.map((template, index) => ({
  ...template,
  number: index + 1,
  previewImage: `/subtitle-templates/${template.id}/preview.png`,
  previewVideo: `/subtitle-templates/${template.id}/preview.mp4`,
  supportedAspectRatios: ["16:9", "9:16", "1:1"],
  defaultParams: {
    ...BASE_CONFIG,
    ...(template.defaultParams || {}),
    primaryColor: template.primary,
    accentColor: template.accent,
  },
}));

export const KINETIC_TEXT_EFFECT_MAP = new Map(KINETIC_TEXT_EFFECTS.map((item) => [item.id, item]));

const LEGACY_TEMPLATE_MAP = new Map([
  ["beat-word-pop", "word-highlight"],
  ["beast-highlight", "keyword-emphasis"],
  ["podcast-lower-third", "dialogue-two-line"],
  ["minimal-subtitle", "documentary-minimal"],
  ["question-pop", "caption-card"],
  ["quote-freeze", "center-statement"],
]);

export function normalizeEffectId(value) {
  const requested = String(value || "").trim();
  const migrated = LEGACY_TEMPLATE_MAP.get(requested) || requested;
  return KINETIC_TEXT_EFFECT_MAP.has(migrated) ? migrated : KINETIC_TEXT_EFFECTS[0].id;
}

export function effectById(value) {
  return KINETIC_TEXT_EFFECT_MAP.get(normalizeEffectId(value));
}

export function defaultEffectParams(effectId) {
  return { ...effectById(effectId).defaultParams };
}

export function motionCanvasProjectDescriptor(project = {}) {
  const template = effectById(project.effectId);
  const aspectRatio = ["16:9", "9:16", "1:1"].includes(project.aspectRatio) ? project.aspectRatio : "9:16";
  const resolution = aspectRatio === "16:9" ? [1920, 1080] : aspectRatio === "1:1" ? [1080, 1080] : [1080, 1920];
  return {
    schema: "subtitle-template-project/v1",
    renderer: "ffmpeg-libass-deterministic",
    visualReferenceCutoff: "2022-01-01",
    resolution,
    frameRate: Number(project.frameRate) === 60 ? 60 : 30,
    aspectRatio,
    template: {
      id: template.id,
      name: template.name,
      renderMode: template.renderMode,
      timingMode: template.timingMode,
      supportedTiming: template.supportedTiming,
      params: { ...template.defaultParams, ...(project.effectParams || {}) },
    },
    segments: (project.segments || []).map((segment) => ({
      id: segment.id,
      startMs: Math.round(Number(segment.start || 0) * 1000),
      endMs: Math.round(Number(segment.end || 0) * 1000),
      text: segment.text,
      words: segment.words || [],
      speaker: segment.speaker || "",
      emphasisWords: segment.keywords || [],
    })),
  };
}
