const BASE_PARAMS = {
  fontFamily: "Microsoft YaHei",
  fontSize: 92,
  x: 50,
  y: 50,
  scale: 100,
  rotationAxis: "none",
  stagger: 0.045,
  introDuration: 0.48,
  holdDuration: 0.25,
};

const EFFECT_DEFS = [
  {
    id: "beat-word-pop",
    name: "爆点词弹跳",
    description: "短视频爆点逐词弹出，重点词放大",
    primary: "#fff6e8",
    accent: "#ffd84d",
    tokenMode: "word",
    layout: "center",
    motion: "pop",
    defaultParams: { fontSize: 104, stagger: 0.055 },
  },
  {
    id: "karaoke-sweep",
    name: "逐词跟读高亮",
    description: "适合口播字幕，当前词扫光高亮",
    primary: "#eef4ff",
    accent: "#62e6ff",
    tokenMode: "word",
    layout: "center",
    motion: "karaoke",
    defaultParams: { fontSize: 88, introDuration: 0.36 },
  },
  {
    id: "mask-rise-line",
    name: "整句上切入",
    description: "高级感整行遮罩上升，干净稳",
    primary: "#ffffff",
    accent: "#b7d5ff",
    tokenMode: "line",
    layout: "center",
    motion: "mask-rise",
    defaultParams: { fontSize: 86, introDuration: 0.58 },
  },
  {
    id: "blur-focus-pull",
    name: "模糊聚焦",
    description: "从虚到实，适合观点转折",
    primary: "#f4f4f0",
    accent: "#ffffff",
    tokenMode: "phrase",
    layout: "center",
    motion: "focus",
    defaultParams: { fontSize: 82, introDuration: 0.62 },
  },
  {
    id: "punch-zoom",
    name: "痛点砸入",
    description: "问题和痛点重锤放大进场",
    primary: "#fff1e6",
    accent: "#ff5c4d",
    tokenMode: "word",
    layout: "impact",
    motion: "slam",
    defaultParams: { fontSize: 112, introDuration: 0.34 },
  },
  {
    id: "glitch-jitter",
    name: "故障抖动",
    description: "焦虑、反差、吐槽类高冲击",
    primary: "#f7fbff",
    accent: "#35f0d0",
    tokenMode: "char",
    layout: "center",
    motion: "glitch",
    defaultParams: { fontSize: 90, stagger: 0.026 },
  },
  {
    id: "neon-pulse",
    name: "霓虹发光",
    description: "描边发光，适合搞怪和夜间感",
    primary: "#fff4fb",
    accent: "#ff7bd5",
    tokenMode: "char",
    layout: "center",
    motion: "neon",
    defaultParams: { fontSize: 90, stagger: 0.03 },
  },
  {
    id: "beast-highlight",
    name: "高对比块字",
    description: "粗体块状高亮，像爆款字幕",
    primary: "#ffffff",
    accent: "#ffe866",
    tokenMode: "phrase",
    layout: "stack",
    motion: "block",
    defaultParams: { fontSize: 96, introDuration: 0.38 },
  },
  {
    id: "hustle-slide",
    name: "快节奏侧滑",
    description: "语速快、信息密度高的侧滑节奏",
    primary: "#f1f5ff",
    accent: "#93b7ff",
    tokenMode: "word",
    layout: "diagonal",
    motion: "slide",
    defaultParams: { fontSize: 86, stagger: 0.035 },
  },
  {
    id: "typewriter-snap",
    name: "逐字打字",
    description: "解释、教学、推理类逐字推进",
    primary: "#eef7ff",
    accent: "#87ffb5",
    tokenMode: "char",
    layout: "line-left",
    motion: "typewriter",
    defaultParams: { fontSize: 78, x: 44, introDuration: 0.72 },
  },
  {
    id: "question-pop",
    name: "疑问句弹窗",
    description: "问题句、反问句做弹窗焦点",
    primary: "#ffffff",
    accent: "#ffcf5a",
    tokenMode: "line",
    layout: "question-card",
    motion: "pop",
    defaultParams: { fontSize: 82, y: 45 },
  },
  {
    id: "quote-freeze",
    name: "金句定格",
    description: "适合结论、金句和转发点",
    primary: "#fffaf0",
    accent: "#f4d35e",
    tokenMode: "line",
    layout: "title-card",
    motion: "wipe",
    defaultParams: { fontSize: 84, introDuration: 0.5 },
  },
  {
    id: "stack-stairs",
    name: "阶梯堆叠",
    description: "关键词阶梯推进，适合步骤讲解",
    primary: "#f6f6f0",
    accent: "#7cc8ff",
    tokenMode: "phrase",
    layout: "stairs",
    motion: "pop",
    defaultParams: { fontSize: 76 },
  },
  {
    id: "main-side-notes",
    name: "主词旁注",
    description: "主词居中，辅助词在两侧铺开",
    primary: "#ffffff",
    accent: "#9cffd1",
    tokenMode: "phrase",
    layout: "side-notes",
    motion: "focus",
    defaultParams: { fontSize: 82 },
  },
  {
    id: "soft-ai-glass",
    name: "柔光玻璃",
    description: "柔和、科技、课程感标题字幕",
    primary: "#eff7ff",
    accent: "#a9cfff",
    tokenMode: "line",
    layout: "center",
    motion: "soft-blur",
    defaultParams: { fontSize: 82, introDuration: 0.66 },
  },
  {
    id: "gaming-stream",
    name: "电竞闪光",
    description: "强发光描边，适合游戏和搞怪",
    primary: "#ffffff",
    accent: "#6cffec",
    tokenMode: "word",
    layout: "impact",
    motion: "neon",
    defaultParams: { fontSize: 102, introDuration: 0.32 },
  },
  {
    id: "podcast-lower-third",
    name: "播客下三分之一",
    description: "稳重底部字幕条，适合长口播",
    primary: "#ffffff",
    accent: "#98c3ff",
    tokenMode: "line",
    layout: "lower-third",
    motion: "wipe",
    defaultParams: { fontSize: 62, y: 76 },
  },
  {
    id: "lyric-wave",
    name: "歌词波浪",
    description: "唱歌、节奏口播、韵律文字",
    primary: "#fff7ed",
    accent: "#ffb0d6",
    tokenMode: "char",
    layout: "wave",
    motion: "wave",
    defaultParams: { fontSize: 86, stagger: 0.032 },
  },
  {
    id: "scatter-assemble",
    name: "散字聚合",
    description: "散开文字聚合为完整句",
    primary: "#f5f6ef",
    accent: "#ffffff",
    tokenMode: "char",
    layout: "scatter",
    motion: "assemble",
    defaultParams: { fontSize: 78, introDuration: 0.58 },
  },
  {
    id: "vertical-slam",
    name: "竖排撞入",
    description: "中文竖向标题，强节奏撞入",
    primary: "#ffffff",
    accent: "#f25f5c",
    tokenMode: "char",
    layout: "vertical",
    motion: "slam",
    defaultParams: { fontSize: 92, introDuration: 0.34 },
  },
  {
    id: "outline-trace",
    name: "描边显影",
    description: "先描边后填充，适合标题感",
    primary: "#fff6ef",
    accent: "#e6b8ff",
    tokenMode: "line",
    layout: "center",
    motion: "outline",
    defaultParams: { fontSize: 86, introDuration: 0.62 },
  },
  {
    id: "sticker-bounce",
    name: "贴纸弹出",
    description: "轻松搞笑类，像贴纸砰出",
    primary: "#fff9e8",
    accent: "#ff8f70",
    tokenMode: "phrase",
    layout: "sticker",
    motion: "elastic",
    defaultParams: { fontSize: 90, introDuration: 0.44 },
  },
  {
    id: "minimal-subtitle",
    name: "极简跟随",
    description: "清爽低干扰，适合严肃内容",
    primary: "#ffffff",
    accent: "#ffffff",
    tokenMode: "line",
    layout: "lower-third",
    motion: "fade",
    defaultParams: { fontSize: 58, y: 78, introDuration: 0.28 },
  },
  {
    id: "keyword-orbit",
    name: "关键词环绕",
    description: "关键词居中，其他词环绕强调",
    primary: "#eef5ff",
    accent: "#d8ff67",
    tokenMode: "word",
    layout: "orbit",
    motion: "orbit",
    defaultParams: { fontSize: 78, introDuration: 0.5 },
  },
];

export const KINETIC_TEXT_EFFECTS = EFFECT_DEFS.map((effect, index) => ({
  ...effect,
  number: index + 1,
  defaultParams: {
    ...BASE_PARAMS,
    ...(effect.defaultParams || {}),
    primaryColor: effect.primary,
    accentColor: effect.accent,
  },
}));

export const KINETIC_TEXT_EFFECT_MAP = new Map(KINETIC_TEXT_EFFECTS.map((item) => [item.id, item]));

export function normalizeEffectId(value) {
  const requested = String(value || "").trim();
  return KINETIC_TEXT_EFFECT_MAP.has(requested) ? requested : KINETIC_TEXT_EFFECTS[0].id;
}

export function effectById(value) {
  return KINETIC_TEXT_EFFECT_MAP.get(normalizeEffectId(value));
}

export function defaultEffectParams(effectId) {
  return { ...effectById(effectId).defaultParams };
}

export function motionCanvasProjectDescriptor(project = {}) {
  const effect = effectById(project.effectId);
  return {
    engine: "motion-canvas",
    engineVersion: "3.17.2",
    renderer: "motion-canvas-2d+ffmpeg",
    resolution: [1920, 1080],
    frameRate: 30,
    effect: {
      id: effect.id,
      number: effect.number,
      name: effect.name,
      layout: effect.layout,
      motion: effect.motion,
      tokenMode: effect.tokenMode,
      params: { ...effect.defaultParams, ...(project.effectParams || {}) },
    },
    scenes: (project.segments || []).map((segment) => ({
      id: segment.id,
      start: segment.start,
      end: segment.end,
      text: segment.text,
      keywords: segment.keywords || [],
      lineBreaks: segment.lineBreaks || [],
      overrides: segment.overrides || {},
    })),
  };
}
